
//created on: 2017.03.29.
package hu.bme.mit.entities
/*



//list any import classes here.
import hu.bme.mit.positioning.*
import org.kie.api.runtime.rule.QueryResults
import java.math.BigDecimal
import java.util.ArrayList
//import hu.bme.mit.utility.CustomTreeMultiset



//declare any global variables here
global hu.bme.mit.toplist.ProfitableAreaToplistSet mostProfitableAreas
global hu.bme.mit.toplist.FrequentRoutesToplistSet mostFrequentRoutes



declare TaxiLog 
@role(event)
@timestamp(dropoff_datetime)
end

declare Tick
@role(event)
@timestamp(currentTime)
@expires( 999ms )
end




declare Route
@role(event)
@timestamp(lastDropoffTime)
end


//Kitörli azokat a TaxiLog rekordokat, amikben nincs meg valamelyik cella, vagyis érvénytelenek. Priroritása miatt elõbb aktiválódik, mint a task1_newTaxiLog szabály
rule task1_removeInvalidTaxiLog
salience 2
	when
		$tlog: TaxiLog(!processed && (pickup_cell == null || dropoff_cell == null))
	then
		retract($tlog);
end

//Az új TaxiLogokat feldolgozó szabály. Aktiválja az utat, (az aktiváló szabály akkor fut le, ha még nincs ilyen Route a WM-ban), illetve
//beilleszt egy RefreshRoute eseményt, majd a processed flag-et beállítja, hogy többet ne fusson már a szabály az adott TaxiLog-ra.
rule task1_newTaxiLogWithoutArea
salience 1
	when
			$tlog:TaxiLog( !processed, $pickupCell: pickup_cell, $dropoffCell: dropoff_cell, $dropoffDate: dropoff_datetime, $inserted : inserted)
			$route:Route(pickup_cell  == $pickupCell, dropoff_cell  == $dropoffCell)
	then
			
			mostFrequentRoutes.remove($route);
			$route.increaseFrequency();
			$route.setDelay(-1);
			$route.setInsertedForDelay($inserted);
			$route.setLastDropoffTime($dropoffDate);
			mostFrequentRoutes.add($route);
			$tlog.setProcessed(true);
			update($route);
			update($tlog);
end

//Létrehoz egy új Route objektumot, ha talál ActivateRoute tényt, és nem talál Route megfelelõt
rule task1_activateRoute
salience 0
	when
		$tlog:TaxiLog( !processed, $pickupCell: pickup_cell, $dropoffCell: dropoff_cell, $dropoffDate: dropoff_datetime, $inserted : inserted)
		not Route($pickupCell == pickup_cell, $dropoffCell == dropoff_cell)
	then
		Route $route = new Route($pickupCell, $dropoffCell,  $dropoffDate , 1);
		$route.setDelay(-1);
		$route.setInsertedForDelay($inserted);
		$tlog.setProcessed(true);
		mostFrequentRoutes.add($route);
		update($tlog);
		insert($route);
end




//A szabály legyûjti azokat a TaxiLog-okat, amik 30 percnél régebbiek, létrehoz egy RefreshRoute eseményt rájuk, majd kitörli õket.
rule task1_removeTaxiLogsFromRoute 
salience -1
	when
		$tick: Tick($ctime : currentTime)
		$tlog:TaxiLog($pickupCell:pickup_cell, $dropoffCell:dropoff_cell ,  this before[30m1s, *] $tick )
		$route: Route(pickup_cell  == $pickupCell, dropoff_cell  == $dropoffCell)
	then
		mostFrequentRoutes.remove($route);
		$route.decreaseFrequency();
		if($route.getFrequency() <= 0){
			retract($route);
		} else{
			mostFrequentRoutes.add($route);
			update($route);
		}
		retract($tlog);
		
end



//For debug
query "routes"  ()

      routes: Route()
end

query "taxis"()
	taxis: TaxiLog()
end*/