//created on: 2017.03.29.
package onlab.event

global onlab.utility.FrequentRoutesToplistSet mostFrequentRoutes
//list any import classes here.

import onlab.positioning.*

//declare any global variables here
declare TaxiLog
@role(event)
@timestamp(dropoff_datetime)
//@expires( 32m )
end

declare Tick
@role(event)
@timestamp(currentTime)
@expires( 1s )
end






rule "TaxiLog_rule"

    when
        $tlog: TaxiLog(!processed ,$pickupCell : pickup_cell , $dropoffCell : dropoff_cell , $dropoffTime : dropoff_datetime)
        $countOfRoutes : java.lang.Number(doubleValue > 0) from accumulate 
        			( TaxiLog( pickup_cell == $pickupCell , dropoff_cell == $dropoffCell, pickup_cell  != null, dropoff_cell != null) over window:time(30m),
        			count()
        			)
    then
    
    	
    	 $tlog.setProcessed(true); 
    	 update($tlog);
    	
    	
    	mostFrequentRoutes.add(new Route($pickupCell, $dropoffCell, $dropoffTime, (java.lang.Long) $countOfRoutes));
  
       
        

end

rule "TaxiLog_decrease"

    when
        $tick:Tick($currentTime : currentTime )
        $tlog:TaxiLog((dropoff_datetime.getTime() + 30 * 60 * 1000) < $currentTime)
    then
    
    	mostFrequentRoutes.decreaseRouteFrequency($tlog.getPickup_cell(), $tlog.getDropoff_cell());
    	retract($tlog);	
       
        

end



